version: '3'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/Data/JuneBlog/frontend/www:/usr/share/nginx/html
      - /home/ubuntu/Data/JuneBlog/log/nginx:/var/log/nginx
      - /home/ubuntu/Data/JuneBlog/frontend/conf:/etc/nginx
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true